# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash', '0002_auto_20170328_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionset',
            name='binary_facts',
            field=models.ManyToManyField(related_name='qsets', to='flash.BinaryFact'),
        ),
    ]
